### ISSUE TITLE
Saliency prediction please

### ISSUE THREAD

**Issue by BarCodeReader** [fupiao1998/TrasformerSOD#3]
the link there is not a valid clickable link to access your predicted saliency map.
please release the map for comparison.

thanks

**Comment by MaoYuxin25** [comment]
I am sorry for my mistake. Maybe you can tell me which experiment saliency map you need and I'll send it to you directly.

**Comment by BarCodeReader** [comment]
Thanks for your reply,
do you mind to share the prediction for DUTS-TE, HKU-IS, PASCAL-S, ECSSD and DUT-OMRON?
maybe a google drive link or baidu disk link?

Thanks a lot

**Comment by MaoYuxin25** [comment]
看到你说可以用百度云，那我就用中文回复了。我的意思是，你需要论文中哪一个任务的saliency map，fully supervision还是weak的。如果你觉得讲不清楚的话，或许你可以通过我的邮箱向我私发你的微信联系。

**Comment by BarCodeReader** [comment]
ok明白了，我这边需要full supervise的。我的意思其实是希望你能公开所有的，大家都能取这样。我私信你吧

**Comment by MaoYuxin25** [comment]
因为最近有一些ddl，所以暂时没时间整理所有的（捂脸），随后会更新的，非常感谢你发现了这个错误。所以如果你着急要的话，我明天先把full supervise的发给你（我没收到你的私信，所以我明天直接把链接更新在这里吧）。

**Comment by MaoYuxin25** [comment]
hello，链接如下：
链接：https://pan.baidu.com/s/1Gg0a8nQZ9g-JlEVo1L6tug 
提取码：wimd

**Comment by BarCodeReader** [comment]
> hello，链接如下： 链接：https://pan.baidu.com/s/1Gg0a8nQZ9g-JlEVo1L6tug 提取码：wimd

謝謝！非常感謝！
